#
#
# æ„Ÿè°¢p3terxå¤§ç¥žçš„ä¸€é”®ç¼–è¯‘è„šæœ¬
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# <https://github.com/danshui-git/Actions-OpenWrt.git>
#
#
#

name: lede-x86-64 å›ºä»¶

on:
  repository_dispatch:

#ç¼–è¾‘ä»»æ„æŒ‡å®šæ–‡ä»¶è§¦å‘å¼€å§‹ç¼–è¯‘
#  push:
#    branches:
#      - master
#    paths:
#      - 'x86-64.config'

#releaseå‘å¸ƒè§¦å‘å¼€å§‹ç¼–è¯‘
#  release:
#    types: published

#å®šæ—¶è§¦å‘å¼€å§‹ç¼–è¯‘(utcæ™‚é–“)
# schedule:
#    - cron: 0 8 2,6,8,30 * *

#ç‚¹æ˜ŸStarè§¦å‘å¼€å§‹ç¼–è¯‘
  watch:
#    types: started

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: x86-64.config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  SSH_ACTIONS: true
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_Release: true
  TZ: Asia/Shanghai
  FILE_NAME: lede/x86/64å›ºä»¶

jobs:
  build:
    name: ç¼–è¯‘OpenWrt-ledeå›ºä»¶
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: å‡†å¤‡å®Œæ¯•
      uses: actions/checkout@main

    - name: å¼€å§‹å®‰è£…ç¼–è¯‘æ‰€éœ€ç³»ç»Ÿ
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: ä¸‹è½½ledeæºç 
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: åŠ è½½DIY_P1_SHè·ŸFEEDS_CONFè®¾ç½®
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: ä¸‹è½½è‡ªå®šä¹‰è½¯ä»¶
      run: cd openwrt && ./scripts/feeds update -a

    - name: å®‰è£…è‡ªå®šä¹‰è½¯ä»¶
      run: cd openwrt && ./scripts/feeds install -a

    - name: åŠ è½½DIY_P2_SHè·ŸCONFIG_FILEè®¾ç½®
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: SSHè¿œç¨‹è¿žæŽ¥æœåŠ¡å™¨é…ç½®å›ºä»¶
      uses: P3TERX/debugger-action@main
      if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')

    - name: ä¸‹è½½æ‰€æœ‰é…ç½®è½¯ä»¶
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: å¼€å§‹ç¼–è¯‘å›ºä»¶
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j2 || make -j2 V=s
        echo "::set-output name=status::success"
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "::set-env name=DEVICE_NAME::_$(cat DEVICE_NAME)"
        echo "::set-env name=FILE_DATE::_$(date +"%Y%m%d%H%M")"

    - name: æ£€æŸ¥githubå‚¨å­˜ç©ºé—´æƒ…å†µ
      if: (!cancelled())
      run: df -hT

    - name: ä¸Šä¼ binæ–‡ä»¶å¤¹(å›ºä»¶+ipk)åœ¨githubç©ºé—´
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_5.4_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: æ•´ç†å›ºä»¶æ–‡ä»¶å¤¹
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$PWD"
        echo "::set-output name=status::success"

    - name: ä¸Šä¼ å›ºä»¶åœ¨githubç©ºé—´
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_5.4_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}


    - name: ä¸Šä¼ å›ºä»¶åˆ°cowtransferç½‘ç›˜
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress ${FIRMWARE} 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"

    - name: ä¸Šä¼ å›ºä»¶åˆ°WeTransferç½‘ç›˜
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"


    - name: Create release
      uses: ncipollo/release-action@v1
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_Release == 'true'
      with:
        name: ${{ env.DATE }} ðŸš€ lede/x86/64å›ºä»¶ | è‡ªåŠ¨ç¼–è¯‘
        allowUpdates: true
        tag: lede-x86-64 å›ºä»¶
        commit: master
        token: ${{ secrets.RELEASES_TOKEN }}
        body: |
          ${{ env.useVersionInfo }}
        artifacts: ${{ env.FIRMWARE }}/*
